### ISSUE TITLE
Please fix homepage in gemspec

### ISSUE THREAD

**Issue by cscheib** [ant31/openapi#1]
Currently set to: `s.homepage = 'http://github.com/antlegrand/openapi'`
Should be: `s.homepage = 'https://github.com/ant31/openapi'`

I was looking for some info on this gem after seeing it pop up on the rubygems.org update Twitter feed.  The link is obviously incorrect, so I wasn't able to easily look anything up regarding this gem.

**Comment by ant31** [comment]
Thx to report this. 

The gem isn't stable yet and not documented yet.

  I've used it to wrap quite large API (private repo) but I've one small example here: 
https://github.com/ant31/varager-ruby,
